name: Build Game
on:
  push: {}

jobs:
  Godot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux, windows, mac]
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      # - name: Build
      #   id: build
      #   uses: manleydev/build-godot-action@v1.4.1
      #   with:
      #     name: example
      #     preset: ${{ matrix.platform }}
      #     debugMode: "true"


      - name: export game
        id: export
        # Use latest version (see releases for all versions)
        uses: firebelley/godot-export@v4.1.0
        with:
          # Defining all the required inputs
          godot_executable_download_url: https://github.com/godotengine/godot/releases/download/3.4.4-stable/Godot_v3.4.4-stable_linux_headless.64.zip
          godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/3.4.4-stable/Godot_v3.4.4-stable_export_templates.tpz
          relative_project_path: ./
          archive_output: true


      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Client - ${{ matrix.platform }}
          path: ${{ steps.export.outputs.archive_directory }}/*
          #path: ${{ github.workspace }}/${{ steps.build.outputs.build }}